name: "xmake"
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
          - os: windows-latest
            platform: mingw --mingw=C:/ProgramData/chocolatey
            arch: x86_64
          - os: macos-latest
            platform: macosx
            arch: x86_64
          - os: macos-latest
            platform: macosx
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - run: xmake f -p ${{ matrix.platform }} -a ${{ matrix.arch }} -y
      - run: xmake b -y
      - run: zip package.zip includes\ lib\
      - uses: actions/upload-artifact@v3
        with:
          name: rjsjai-${{ matrix.platform }}-${{ matrix.arch }}
          path: package.zip
