name: "xmake"
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

env:
  SERVER_HOST: ai.leavelet.io
  SERVER_PORT: 443

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
          - os: windows-latest
            platform: mingw
            extra_args: --mingw=C:/ProgramData/chocolatey
            arch: x86_64
          - os: macos-latest
            platform: macosx
            arch: x86_64
          - os: macos-latest
            platform: macosx
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - run: xmake f -p ${{ matrix.platform }} -a ${{ matrix.arch }} -y ${{ matrix.extra_args }}
      - run: xmake b -y
      - uses: actions/upload-artifact@v3
        with:
          name: rjsjai-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            includes/*
            lib/*
